affine_trainable: false
auto_save: true
base_fun_name: silu
ckpt_path: ./model
device: cpu
grid: 10
grid_eps: 1.0
grid_range:
- -1
- 1
k: 3
mult_arity: 2
round: 0
sb_trainable: true
sp_trainable: true
state_id: 7
symbolic.funs_name.0:
- - sin
  - x^2
symbolic.funs_name.1:
- - exp
symbolic_enabled: true
width:
- - 2
  - 0
- - 1
  - 0
- - 1
  - 0
