affine_trainable: false
auto_save: true
base_fun_name: silu
ckpt_path: ./model
grid: 3
grid_eps: 1.0
grid_range:
- -1
- 1
k: 3
mult_arity: 2
round: 0
sb_trainable: true
sp_trainable: true
state_id: 14
symbolic.funs_name.0:
- - '0'
  - '0'
- - '0'
  - '0'
- - '0'
  - '0'
symbolic.funs_name.1:
- - '0'
  - '0'
  - '0'
- - '0'
  - '0'
  - '0'
symbolic.funs_name.2:
- - '0'
  - '0'
symbolic_enabled: true
width:
- - 2
  - 0
- - 3
  - 0
- - 2
  - 0
- - 1
  - 0
