affine_trainable: false
auto_save: true
base_fun_name: !!python/object:torch.nn.modules.activation.SiLU
  _backward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _backward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _buffers: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks_always_called: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
  - []
  _is_full_backward_hook: null
  _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _modules: !!python/object/apply:collections.OrderedDict
  - []
  _non_persistent_buffers_set: !!set {}
  _parameters: !!python/object/apply:collections.OrderedDict
  - []
  _state_dict_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  inplace: false
  training: true
ckpt_path: ./model
grid: 3
grid_eps: 1.0
grid_range:
- -1
- 1
k: 3
mult_arity: 2
round: 0
sb_trainable: true
sp_trainable: true
state_id: 5
symbolic.funs_name.0:
- - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
symbolic.funs_name.1:
- - '0'
symbolic.funs_name.2:
- - '0'
symbolic_enabled: true
width:
- - 46
  - 0
- - 1
  - 0
- - 1
  - 0
- - 1
  - 0
