affine_trainable: false
auto_save: true
base_fun_name: silu
ckpt_path: ./model
device: cuda
grid: 5
grid_eps: 1.0
grid_range:
- -1
- 1
k: 3
mult_arity: 2
round: 1
sb_trainable: true
sp_trainable: true
state_id: 2
symbolic.funs_name.0:
- - '0'
  - '0'
- - '0'
  - '0'
- - '0'
  - '0'
- - '0'
  - '0'
- - '0'
  - '0'
symbolic.funs_name.1:
- - '0'
  - '0'
  - '0'
  - '0'
  - '0'
symbolic_enabled: false
width:
- - 2
  - 0
- - 5
  - 0
- - 1
  - 0
