affine_trainable: false
auto_save: true
base_fun_name: silu
ckpt_path: ./model
grid: 5
grid_eps: 1.0
grid_range:
- -1
- 1
k: 3
mult_arity: 2
round: 1
sb_trainable: true
sp_trainable: true
state_id: 6
symbolic.funs_name.0:
- - x^2
  - x^2
symbolic.funs_name.1:
- - sqrt
symbolic_enabled: true
width:
- - 2
  - 0
- - 1
  - 0
- - 1
  - 0
